name: Publish Users Service Container

on:
  push:
    branches: [ main ]
    paths:
      - 'services/users-service/**'
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/common/common-publish-container.yml
    with:
      service_path: 'services/users-service'
      image_name: 'ghcr.io/${{ github.repository_owner }}/users-service'
      dockerfile: 'Dockerfile'
      tags: 'latest'
